---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/vms/role/prometheus"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
