---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "vms/roles/prometheus/templates/*"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
