---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl

- name: Run multiline shell script
  ansible.builtin.shell: |
    #!/bin/bash
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - gitlab-ce=16.6.0-ce.0

- name: Copy credentials file
  template:
    src: templates/credentials.j2
    dest: "/etc/gitlab/credentials"
    mode: "0755"
- name: Run multiline shell script
  ansible.builtin.shell: |
    #!/bin/bash
    # Clean up
    apt-get -y --purge remove linux-headers-$(uname -r) build-essential
    apt-get -y --purge autoremove
    apt-get -y purge $(dpkg --list |grep '^rc' |awk '{print $2}')
    apt-get -y purge $(dpkg --list |egrep 'linux-image-[0-9]' |awk '{print $3,$2}' |sort -nr |tail -n +2 |grep -v $(uname -r) |awk '{ print $2}')
    apt-get -y clean

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes
