---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker.io
    - docker-compose
    - cloud-init

- name: Create directory for app
  file:
    path: "{{prometheus_dir}}"
    state: directory
    mode: 0755

# - name: Create directory for data prometheus
#   become: true
#   file:
#     path: "{{prometheus_dir}}/data/prometheus"
#     state: directory
#     mode: 0777

# - name: Create directory for data alertmanager
#   become: true
#   file:
#     path: "{{prometheus_dir}}/data/alertmanager"
#     state: directory
#     mode: 0777

# - name: Create directory for prometheus
#   file:
#     path: "{{prometheus_dir}}/config"
#     state: directory
#     mode: 0755

# - name: Copy grafana datasource file
#   template:
#     src: templates/datasource.yml
#     dest: "{{prometheus_dir}}/config/datasource.yml"
#     mode: 0755

# - name: Copy alert.yml
#   template:
#     src: templates/alert.rules.j2
#     dest: "{{prometheus_dir}}/config/alert.yml"
#     mode: 0755

# - name: Copy alertmanager.yml
#   template:
#     src: templates/alertmanager.yml.j2
#     dest: "{{prometheus_dir}}/config/alertmanager.yml"
#     mode: 0755

# - name: Copy prometheus.yml
#   template:
#     src: templates/prometheus.yml
#     dest: "{{prometheus_dir}}/config/prometheus.yml"
#     mode: 0755

# - name: Copy .env
#   template:
#     src: templates/.env.j2
#     dest: "{{prometheus_dir}}/.env"
#     mode: 0755

# - name: Copy docker compose file
#   template:
#     src: templates/docker-compose.yml.j2
#     dest: "{{ prometheus_dir }}/docker-compose.yml"
#     group: www-data
#     mode: 0440

# - name: Create startup.sh
#   become: true
#   template:
#     src: templates/start.sh.j2
#     dest: "{{ prometheus_dir }}/startup.sh"
#     owner: root
#     mode: 0755

# - name: Create systemd service
#   become: true
#   template:
#     src: templates/service.j2
#     dest: /etc/systemd/system/prometheus.service
#     owner: root
#     mode: 0644
# - name: Enable service
#   systemd:
#     name: prometheus
#     enabled: yes
# - name: pull an image
#   become: true
#   docker_image:
#     name: "{{ item }}"
#     source: pull
#     pull:
#       platform: amd64
#   with_items:
#     - prom/alertmanager:{{ ALERTMANAGER_TAG }}
#     - prom/prometheus:{{ PROMETHEUS_TAG }}
#     - prom/node-exporter:{{ NODE_EXPORTER_TAG }}
#     - grafana/grafana:{{ GRAFANA_TAG }}

# - name: Create a network
#   become: true
#   docker_network:
#     name: prometheus

# - name: deploy Docker Compose stack
#   become: true
#   community.docker.docker_compose:
#     project_src: /opt/prometheus
#     files:
#     - docker-compose.yml

- name: Copy cleanup file
  template:
    src: templates/cleanup.sh
    dest: "{{prometheus_dir}}/cleanup.sh"
    mode: 0755

- name: This command will change the working directory to somedir/
  become: true
  ansible.builtin.shell:
    cmd: ./cleanup.sh
    chdir: "{{prometheus_dir}}"
