---
global:
  scrape_interval: 30s
  scrape_timeout: 10s
rule_files:
  - alert.yml
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
    scheme: http
  - job_name: node-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node-exporter:9100'
    scheme: http
  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'grafana:3000'
    scheme: http
